# Generated by Django 5.0 on 2023-12-15 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0002_remove_alumno_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='mail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
