# Generated by Django 5.0 on 2023-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0003_alumno_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='escuela',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='nota',
            new_name='codigo',
        ),
    ]
