# Generated by Django 5.0 on 2023-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0004_profesor_delete_escuela_rename_nota_materia_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
